export type NounClass =
  | 'weapon'
  | 'art'
  | 'beast'
  | 'ghost'
  | 'demon'
  | 'place'
  | 'herb'
  | 'pill'
  | 'body';

export interface Mod {
  text: string;
  tags: string[];
  bands: number[];
}

export interface Noun {
  text: string;
  cls: NounClass;
  bands: number[];
}

export const COMPAT: Record<string, NounClass[]> = {
  青: ['weapon', 'art'],
  赤: ['weapon', 'art'],
  玄: ['weapon', 'art', 'art'],
  白骨: ['weapon', 'beast', 'ghost', 'demon'],
  寒: ['weapon', 'art', 'place', 'body'],
  残: ['weapon', 'art', 'ghost', 'place'],
  古: ['weapon', 'art', 'place', 'pill'],
  月: ['weapon', 'art', 'place', 'body'],
  星: ['weapon', 'art', 'body', 'pill'],
  雾: ['ghost', 'place', 'pill'],
  云: ['place', 'body', 'art'],
  雷: ['weapon', 'art', 'body', 'beast'],
  火: ['weapon', 'art', 'body', 'beast'],
  水: ['place', 'body', 'herb', 'pill'],
  木: ['herb', 'place', 'body'],
  土: ['place', 'body'],
  金: ['weapon', 'art', 'body'],
  血: ['weapon', 'beast', 'demon', 'body'],
  幽: ['ghost', 'place', 'pill'],
  沉: ['place', 'body'],
  流: ['weapon', 'art', 'place'],
  断: ['weapon', 'place', 'body'],
  焚: ['beast', 'demon', 'weapon'],
  噬: ['beast', 'ghost', 'demon'],
  吞: ['beast', 'demon'],
  枯: ['place', 'herb', 'body'],
  春: ['herb', 'place', 'body'],
  秋: ['place', 'herb', 'weapon'],
  双子: ['beast', 'body', 'art'],
  三眼: ['beast', 'demon', 'body'],
  独眼: ['beast', 'demon'],
  无相: ['ghost', 'demon', 'body'],
  长夜: ['ghost', 'place'],
  荒: ['place', 'beast'],
  绝: ['place', 'weapon', 'body'],
  太虚: ['art', 'place', 'pill', 'body'],
  混元: ['art', 'body', 'pill'],
  大罗: ['art', 'body'],
  仙: ['art', 'pill', 'body', 'weapon'],
  道: ['art', 'body', 'pill'],
  一炁: ['body', 'art', 'pill'],
  万象: ['art', 'place', 'body'],
  钧天: ['place', 'art'],
  赤霄: ['weapon', 'art', 'place'],
  紫府: ['place', 'body', 'pill'],
  玉京: ['place', 'art'],
  沧溟: ['place', 'body', 'ghost'],
  幽都: ['place', 'ghost', 'demon'],
  天: ['place', 'body', 'art'],
  地: ['place', 'body'],
  人: ['body', 'art'],
  药: ['herb', 'pill'],
  丹: ['pill', 'body'],
  魂: ['ghost', 'demon', 'body', 'weapon'],
  魄: ['ghost', 'body'],
  山: ['place', 'beast'],
  石: ['place', 'body', 'art'],
  碧: ['herb', 'place', 'art'],
  素: ['art', 'pill', 'body'],
  浮: ['place', 'ghost'],
  裂: ['weapon', 'place', 'body'],
  灼: ['beast', 'weapon', 'body'],
  冷: ['ghost', 'place', 'weapon'],
};

export const MODS: Mod[] = [
  { text: '青', tags: ['青'], bands: [0, 1, 2] },
  { text: '赤', tags: ['赤'], bands: [0, 1, 2] },
  { text: '玄', tags: ['玄'], bands: [0, 1, 2, 3, 4] },
  { text: '白骨', tags: ['白骨'], bands: [1, 2, 3] },
  { text: '寒', tags: ['寒'], bands: [0, 1, 2, 3] },
  { text: '残', tags: ['残'], bands: [0, 1, 2] },
  { text: '古', tags: ['古'], bands: [1, 2, 3] },
  { text: '月', tags: ['月'], bands: [0, 1, 2, 3] },
  { text: '星', tags: ['星'], bands: [1, 2, 3, 4] },
  { text: '雾', tags: ['雾'], bands: [0, 1, 2] },
  { text: '云', tags: ['云'], bands: [1, 2, 3] },
  { text: '雷', tags: ['雷'], bands: [1, 2, 3] },
  { text: '火', tags: ['火'], bands: [0, 1, 2] },
  { text: '水', tags: ['水'], bands: [0, 1, 2] },
  { text: '木', tags: ['木'], bands: [0, 1, 2] },
  { text: '土', tags: ['土'], bands: [0, 1] },
  { text: '金', tags: ['金'], bands: [1, 2, 3] },
  { text: '血', tags: ['血'], bands: [1, 2, 3] },
  { text: '幽', tags: ['幽'], bands: [1, 2, 3, 4] },
  { text: '沉', tags: ['沉'], bands: [1, 2] },
  { text: '流', tags: ['流'], bands: [0, 1, 2] },
  { text: '断', tags: ['断'], bands: [0, 1, 2] },
  { text: '焚', tags: ['焚'], bands: [1, 2, 3] },
  { text: '噬', tags: ['噬'], bands: [1, 2, 3] },
  { text: '吞', tags: ['吞'], bands: [1, 2] },
  { text: '枯', tags: ['枯'], bands: [1, 2] },
  { text: '春', tags: ['春'], bands: [0, 1] },
  { text: '秋', tags: ['秋'], bands: [0, 1] },
  { text: '双子', tags: ['双子'], bands: [1, 2, 3] },
  { text: '三眼', tags: ['三眼'], bands: [1, 2, 3] },
  { text: '独眼', tags: ['独眼'], bands: [0, 1, 2] },
  { text: '无相', tags: ['无相'], bands: [2, 3, 4] },
  { text: '长夜', tags: ['长夜'], bands: [2, 3, 4] },
  { text: '荒', tags: ['荒'], bands: [0, 1, 2] },
  { text: '绝', tags: ['绝'], bands: [1, 2, 3] },
  { text: '太虚', tags: ['太虚'], bands: [3, 4] },
  { text: '混元', tags: ['混元'], bands: [3, 4] },
  { text: '大罗', tags: ['大罗'], bands: [3, 4] },
  { text: '仙', tags: ['仙'], bands: [2, 3, 4] },
  { text: '道', tags: ['道'], bands: [2, 3, 4] },
  { text: '一炁', tags: ['一炁'], bands: [3, 4] },
  { text: '万象', tags: ['万象'], bands: [2, 3, 4] },
  { text: '钧天', tags: ['钧天'], bands: [3, 4] },
  { text: '赤霄', tags: ['赤霄'], bands: [3, 4] },
  { text: '紫府', tags: ['紫府'], bands: [2, 3, 4] },
  { text: '玉京', tags: ['玉京'], bands: [3, 4] },
  { text: '沧溟', tags: ['沧溟'], bands: [3, 4] },
  { text: '幽都', tags: ['幽都'], bands: [3, 4] },
  { text: '天', tags: ['天'], bands: [1, 2, 3, 4] },
  { text: '地', tags: ['地'], bands: [1, 2, 3] },
  { text: '人', tags: ['人'], bands: [0, 1, 2] },
  { text: '药', tags: ['药'], bands: [0, 1, 2] },
  { text: '丹', tags: ['丹'], bands: [1, 2, 3] },
  { text: '魂', tags: ['魂'], bands: [1, 2, 3, 4] },
  { text: '魄', tags: ['魄'], bands: [1, 2, 3] },
  { text: '山', tags: ['山'], bands: [0, 1, 2] },
  { text: '石', tags: ['石'], bands: [0, 1, 2] },
  { text: '碧', tags: ['碧'], bands: [0, 1, 2] },
  { text: '素', tags: ['素'], bands: [1, 2, 3] },
  { text: '浮', tags: ['浮'], bands: [1, 2, 3] },
  { text: '裂', tags: ['裂'], bands: [1, 2, 3] },
  { text: '灼', tags: ['灼'], bands: [1, 2, 3] },
  { text: '冷', tags: ['冷'], bands: [1, 2, 3, 4] },
  { text: '无咎', tags: ['无相'], bands: [3, 4] },
  { text: '大千', tags: ['万象'], bands: [3, 4] },
  { text: '三千', tags: ['万象'], bands: [3, 4] },
  { text: '离恨', tags: ['幽'], bands: [3, 4] },
  { text: '忘川', tags: ['幽'], bands: [3, 4] },
  { text: '重华', tags: ['星'], bands: [3, 4] },
  { text: '烛照', tags: ['星'], bands: [3, 4] },
  { text: '玄冥', tags: ['玄'], bands: [3, 4] },
  { text: '青冥', tags: ['青'], bands: [3, 4] },
  { text: '赤明', tags: ['赤'], bands: [3, 4] },
  { text: '素女', tags: ['素'], bands: [3, 4] },
  { text: '龙汉', tags: ['古'], bands: [3, 4] },
  { text: '延康', tags: ['古'], bands: [3, 4] },
  { text: '元始', tags: ['道'], bands: [4] },
  { text: '灵宝', tags: ['道'], bands: [4] },
  { text: '洞真', tags: ['仙'], bands: [4] },
  { text: '金阙', tags: ['玉京'], bands: [4] },
  { text: '瑶池', tags: ['玉京'], bands: [3, 4] },
  { text: '天枢', tags: ['星'], bands: [3, 4] },
  { text: '紫微', tags: ['星'], bands: [3, 4] },
  { text: '昆仑', tags: ['山'], bands: [3, 4] },
  { text: '碧游', tags: ['碧'], bands: [3, 4] },
  { text: '血河', tags: ['血'], bands: [3, 4] },
  { text: '焚天', tags: ['焚'], bands: [3, 4] },
  { text: '裂空', tags: ['裂'], bands: [3, 4] },
  { text: '灼阳', tags: ['灼'], bands: [3, 4] },
  { text: '寒洲', tags: ['寒'], bands: [2, 3, 4] },
];

export const NOUNS: Noun[] = [
  { text: '狼', cls: 'beast', bands: [0, 1] },
  { text: '虎', cls: 'beast', bands: [0, 1] },
  { text: '蟒', cls: 'beast', bands: [0, 1, 2] },
  { text: '猿', cls: 'beast', bands: [0, 1, 2] },
  { text: '鹰', cls: 'beast', bands: [0, 1] },
  { text: '蛇', cls: 'beast', bands: [0, 1] },
  { text: '獾', cls: 'beast', bands: [0] },
  { text: '蜈蚣', cls: 'beast', bands: [0, 1] },
  { text: '山魈', cls: 'beast', bands: [1, 2] },
  { text: '蛟', cls: 'beast', bands: [1, 2, 3] },
  { text: '犀', cls: 'beast', bands: [1, 2] },
  { text: '鸦', cls: 'beast', bands: [1, 2] },
  { text: '螭', cls: 'beast', bands: [2, 3, 4] },
  { text: '鲲', cls: 'beast', bands: [3, 4] },
  { text: '麟', cls: 'beast', bands: [3, 4] },
  { text: '鬼火', cls: 'ghost', bands: [0, 1] },
  { text: '野魂', cls: 'ghost', bands: [0, 1] },
  { text: '怨灵', cls: 'ghost', bands: [1, 2] },
  { text: '阴煞', cls: 'ghost', bands: [1, 2, 3] },
  { text: '厉魄', cls: 'ghost', bands: [1, 2, 3] },
  { text: '残念', cls: 'ghost', bands: [2, 3] },
  { text: '道影', cls: 'ghost', bands: [3, 4] },
  { text: '劫影', cls: 'ghost', bands: [3, 4] },
  { text: '藤妖', cls: 'demon', bands: [0, 1] },
  { text: '石灵', cls: 'demon', bands: [0, 1] },
  { text: '木魅', cls: 'demon', bands: [1, 2] },
  { text: '血魔', cls: 'demon', bands: [2, 3] },
  { text: '心魔', cls: 'demon', bands: [2, 3, 4] },
  { text: '天魔', cls: 'demon', bands: [3, 4] },
  { text: '外道', cls: 'demon', bands: [2, 3, 4] },
  { text: '剑修', cls: 'art', bands: [0, 1] },
  { text: '刀客', cls: 'art', bands: [0, 1] },
  { text: '枪仙', cls: 'art', bands: [2, 3] },
  { text: '符师', cls: 'art', bands: [1, 2] },
  { text: '阵师', cls: 'art', bands: [1, 2, 3] },
  { text: '丹师', cls: 'art', bands: [1, 2] },
  { text: '剑冢', cls: 'place', bands: [1, 2] },
  { text: '坟冢', cls: 'place', bands: [0, 1] },
  { text: '荒庙', cls: 'place', bands: [0, 1] },
  { text: '洞窟', cls: 'place', bands: [0, 1] },
  { text: '断碑', cls: 'place', bands: [0, 1] },
  { text: '古渡', cls: 'place', bands: [1, 2] },
  { text: '雷池', cls: 'place', bands: [2, 3] },
  { text: '仙墟', cls: 'place', bands: [3, 4] },
  { text: '道场', cls: 'place', bands: [3, 4] },
  { text: '星海', cls: 'place', bands: [3, 4] },
  { text: '灵草', cls: 'herb', bands: [0, 1] },
  { text: '芝', cls: 'herb', bands: [1, 2] },
  { text: '幽兰', cls: 'herb', bands: [1, 2] },
  { text: '果', cls: 'herb', bands: [0, 1] },
  { text: '丹', cls: 'pill', bands: [0, 1, 2] },
  { text: '丹方', cls: 'pill', bands: [1, 2] },
  { text: '残丹', cls: 'pill', bands: [1, 2] },
  { text: '道果', cls: 'pill', bands: [3, 4] },
  { text: '骨', cls: 'body', bands: [0, 1] },
  { text: '筋', cls: 'body', bands: [0, 1] },
  { text: '血', cls: 'body', bands: [1, 2] },
  { text: '心', cls: 'body', bands: [1, 2] },
  { text: '道体', cls: 'body', bands: [3, 4] },
  { text: '妖丹', cls: 'pill', bands: [2, 3, 4] },
  { text: '鬼车', cls: 'ghost', bands: [2, 3, 4] },
  { text: '灵胎', cls: 'body', bands: [2, 3, 4] },
  { text: '魔影', cls: 'ghost', bands: [2, 3, 4] },
  { text: '血蛟', cls: 'beast', bands: [2, 3, 4] },
  { text: '石胎', cls: 'body', bands: [2, 3, 4] },
  { text: '道兵', cls: 'art', bands: [3, 4] },
  { text: '星骸', cls: 'place', bands: [3, 4] },
  { text: '仙傀', cls: 'art', bands: [3, 4] },
  { text: '天罡', cls: 'place', bands: [3, 4] },
  { text: '雷髓', cls: 'pill', bands: [2, 3, 4] },
  { text: '玄蟒', cls: 'beast', bands: [3, 4] },
  { text: '霜鳞', cls: 'beast', bands: [2, 3] },
  { text: '幽篁', cls: 'place', bands: [2, 3, 4] },
  { text: '古篆', cls: 'art', bands: [2, 3] },
  { text: '枯禅', cls: 'body', bands: [2, 3] },
  { text: '残卷', cls: 'art', bands: [1, 2, 3] },
  { text: '药王', cls: 'pill', bands: [1, 2, 3] },
  { text: '灵枢', cls: 'herb', bands: [2, 3] },
  { text: '朱果', cls: 'herb', bands: [1, 2, 3] },
  { text: '碧螺', cls: 'herb', bands: [1, 2, 3] },
  { text: '黄庭', cls: 'place', bands: [2, 3, 4] },
  { text: '苍梧', cls: 'place', bands: [1, 2, 3] },
  { text: '赤壁', cls: 'place', bands: [0, 1, 2] },
  { text: '寒潭', cls: 'place', bands: [0, 1, 2] },
  { text: '蛇窟', cls: 'place', bands: [0, 1] },
  { text: '狼穴', cls: 'place', bands: [0, 1] },
  { text: '猎户', cls: 'art', bands: [0, 1] },
  { text: '药农', cls: 'art', bands: [0, 1] },
  { text: '石匠', cls: 'art', bands: [0, 1] },
];

export const ARTIFACT_MATS: Mod[] = MODS.filter((m) =>
  m.tags.some((t) => COMPAT[t]?.some((c) => c === 'weapon' || c === 'art' || c === 'place')),
);

export const ARTIFACT_NOUNS: Noun[] = NOUNS.filter(
  (n) =>
    n.cls === 'weapon' ||
    n.cls === 'art' ||
    n.cls === 'place' ||
    n.cls === 'body' ||
    n.cls === 'pill',
);

// 档位后缀词：名称 = 修饰 + 名词 + 档位词（+ 法宝后缀）。
// 三槽组合是满足「每档 ≥120 条且跨档不重复」的必要条件。
export const RANK: Record<number, string[]> = {
  0: ['兽', '精', '妖'],
  1: ['妖', '魔', '灵', '王'],
  2: ['妖', '魔', '灵', '王', '将'],
  3: ['将', '君', '尊', '主', '灵'],
  4: ['帝', '祖', '圣', '尊', '君'],
};

export const ARTIFACT_SUFFIX: Record<number, string[]> = {
  0: ['剑', '刀', '印', '铃', '幡', '珠', '镜', '环', '匣', '笔', '伞', '梭', '尺', '钩', '匕', '符'],
  1: ['剑', '印', '铃', '幡', '珠', '镜', '环', '匣', '笔', '伞', '梭', '尺', '钩', '匕', '符', '壶', '盘', '轮'],
  2: ['剑', '印', '幡', '珠', '镜', '环', '匣', '尺', '鼎', '钟', '塔', '灯', '壶', '盘', '轮', '碑', '令', '盘'],
  3: ['印', '珠', '镜', '鼎', '钟', '塔', '灯', '碑', '壶', '轮', '盘', '宫', '令', '玺', '幢', '幢'],
  4: ['印', '珠', '镜', '鼎', '钟', '塔', '碑', '轮', '盘', '宫', '殿', '壶', '玺', '幢', '冕', '符'],
};

export const BLOCKLIST: string[] = [];

export const BANDS: { tiers: number[] }[] = [
  { tiers: [1, 2, 3, 4] },
  { tiers: [5, 6, 7, 8] },
  { tiers: [9, 10, 11, 12] },
  { tiers: [13, 14, 15, 16] },
  { tiers: [17, 18, 19, 20] },
];

export const NAME_LENGTH: { maxTier: number; lo: number; hi: number }[] = [
  { maxTier: 3, lo: 3, hi: 5 },
  { maxTier: 7, lo: 4, hi: 6 },
  { maxTier: 10, lo: 5, hi: 8 },
  { maxTier: 20, lo: 5, hi: 9 },
];
